## Numpy:

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

## One_dimensional

In [6]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

dtype('int32')

In [9]:
a = np.array(['a','b',3,4])
a

array(['a', 'b', '3', '4'], dtype='<U1')

In [10]:
a.dtype

dtype('<U1')

In [11]:
a = np.append(a,12)

In [12]:
a

array(['a', 'b', '3', '4', '12'], dtype='<U11')

In [15]:
b = np.arange(0,10)        ### a_range of 1 to 10
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
b = np.arange(0,10,2)        ### a_range of 1 to 10 with step 2
b

array([0, 2, 4, 6, 8])

In [17]:
b.nbytes  ### checking memory occupied by array(b)

20

In [18]:
b.itemsize    ### size of each element

4

In [19]:
len(b)      ### no. of elements in the array(b)

5

In [22]:
### geting array of n elements from 1 to x:                 n=20   x=10
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [23]:
np.logspace(1,10,20)

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [24]:
### HELP
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [25]:
### create an array with same word for x times:       (no_of-times , req_value/int)
np.full(10,"hello")

array(['hello', 'hello', 'hello', 'hello', 'hello', 'hello', 'hello',
       'hello', 'hello', 'hello'], dtype='<U5')

In [26]:
np.full(3,7,dtype = "float32")              ### storing 7 as float in array  ( 3 times  )

array([7., 7., 7.], dtype=float32)

In [29]:
np.full(3,7,dtype = 'complex')

array([7.+0.j, 7.+0.j, 7.+0.j])

In [30]:
### getting only imaginary
np.full(4,5j)

array([0.+5.j, 0.+5.j, 0.+5.j, 0.+5.j])

In [27]:
### stoeing ones for x times:
np.ones(10, dtype = "int")

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [28]:
np.zeros(4)              ### default as floats

array([0., 0., 0., 0.])

## Two_dimensional

In [39]:
import numpy as np
d = np.array([[1,2,3,4],[1,2,3,4]])

In [40]:
d

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [45]:
d.ndim     ### checking dimensions of array(1d,2d,.....)

2

In [47]:
li = d.shape    ### shape of array------ORDER
print(li)
type(li)

(2, 4)


tuple

In [42]:
d.nbytes

32

In [43]:
d.itemsize

4

In [44]:
len(d)    ### no. of rows

2

## Three_dimensional

In [82]:
### combination of two dimensional arrays
t = np.array([[[1,2,3,4],[2,3,4,5]],[[3,4,5,6],[5,6,7,8]]])

In [83]:
t

array([[[1, 2, 3, 4],
        [2, 3, 4, 5]],

       [[3, 4, 5, 6],
        [5, 6, 7, 8]]])

In [50]:
len(t)     ### n0. of 2d arrays present

2

In [51]:
t.shape       ### (no. of arrays , no. of rows , no. of columns)

(2, 2, 4)

In [52]:
t.nbytes

64

In [53]:
t.itemsize

4

In [54]:
t.ndim

3

## Multi_dimensional

In [56]:
s = np.array([1,2,3,4],ndmin=5)
s

array([[[[[1, 2, 3, 4]]]]])

In [57]:
s.ndim

5

### Accessing the elements from the array

In [58]:
a

array(['a', 'b', '3', '4', '12'], dtype='<U11')

In [59]:
b

array([0, 2, 4, 6, 8])

In [60]:
b[2]

4

In [61]:
b[2:4]

array([4, 6])

In [62]:
b[-1]

8

In [63]:
b[1:]

array([2, 4, 6, 8])

In [64]:
### 2d


d

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [65]:
d[0]  ### single value ----- row

array([1, 2, 3, 4])

In [66]:
d[-1]

array([1, 2, 3, 4])

In [67]:
d[0][2:]

array([3, 4])

In [69]:
d[0,-1]    ### [row_index , element-index]

4

In [73]:
d[:,-1]

array([4, 4])

In [72]:
d[:,2:]

array([[3, 4],
       [3, 4]])

In [74]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
### [2,3] , [10,11]
x[::2,1:3]

array([[ 2,  3],
       [10, 11]])

In [77]:
### [3,7,11]
x[:,-2]

array([ 3,  7, 11])

In [84]:
### 3d

t

array([[[1, 2, 3, 4],
        [2, 3, 4, 5]],

       [[3, 4, 5, 6],
        [5, 6, 7, 8]]])

In [85]:
t[0]

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [86]:
t[0,0]

array([1, 2, 3, 4])

In [87]:
 t[0,0,2]

3

In [88]:
t[:,:,2:]

array([[[3, 4],
        [4, 5]],

       [[5, 6],
        [7, 8]]])

In [89]:
t

array([[[1, 2, 3, 4],
        [2, 3, 4, 5]],

       [[3, 4, 5, 6],
        [5, 6, 7, 8]]])

In [92]:
t[:,0,:2]

array([[1, 2],
       [3, 4]])

In [93]:




  -------------->selecting both two
  |  ----------->selecting second row
  |  |  -------->selecting last two columns
  |  |  |
  |  |  |
  |  |  |
t[:,1:,2:]

array([[[4, 5]],

       [[7, 8]]])

In [94]:
a

array(['a', 'b', '3', '4', '12'], dtype='<U11')

In [96]:
np.append(a,[1,2,3,4])           ### appending multiple elements

array(['a', 'b', '3', '4', '12', '1', '2', '3', '4'], dtype='<U11')

## Shape of arrays

In [97]:
###   1--d array
a.shape    ###no  -of_rows/elements

(5,)

In [98]:
###  2--d array
d.shape     ### n_of_rows, no_0f_col

(2, 4)

In [99]:
###    3---d array
t.shape   ### n_of_2-d arrays, n_of_rows, n_of_col

(2, 2, 4)

## Reshaping of arrays
 * changing dimensions of the array

In [100]:
a = np.arange(1,9)
a.ndim

1

In [106]:
v = a.reshape(2,4)  ### rows, cols
v

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [105]:
v.shape

(2, 4)

In [107]:
v.ndim

2

In [110]:
g = v.reshape(8,1)

In [111]:
g

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [112]:
k = a.reshape(2,2,2)

In [113]:
k

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [114]:
b = np.arange(1,20,2)

In [115]:
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [116]:
len(b)

10

In [117]:
### possible reshapes od array---b
b.reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [118]:
b.reshape(5,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [119]:
b.reshape(10,1)

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19]])

In [121]:
b.reshape(1,2,5)

array([[[ 1,  3,  5,  7,  9],
        [11, 13, 15, 17, 19]]])

In [122]:
b.reshape(2,5,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [123]:
b.reshape(2,1,5)

array([[[ 1,  3,  5,  7,  9]],

       [[11, 13, 15, 17, 19]]])

In [124]:
b.reshape(5,2,1)

array([[[ 1],
        [ 3]],

       [[ 5],
        [ 7]],

       [[ 9],
        [11]],

       [[13],
        [15]],

       [[17],
        [19]]])

In [125]:
b.reshape(2,-1)   ### if we don't know no.of cols

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [126]:
b.reshape(5,-1)     ### if we don't know no.of cols

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [127]:
b.reshape(-1,2)      ### if we don't know no.of rows

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])